### PR TITLE
Fix margins between the sections

### PR DESCRIPTION
**Pull request by shrinathprabhu**
# Resolves

- [AR-3418](https://team-1624093970686.atlassian.net/browse/AR-3418)

## Changes

- Fixed spacing between hero title, hero description and hero cta buttons 

# Screenshots
Before
Screenshot from 2022-07-25 18-31-30

After
Screenshot from 2022-07-25 18-34-04

# Checklist

- [x] The branch name follows the format: `developer-name/AR-XXX-issue-name`.
- [x] The changes have been tested locally.

### CODE REVIEW

**Review by ajithranka — CHANGES_REQUESTED** [review]
Screenshot 2022-07-26 at 12 14 31 AM

Looks off on small screens. Check if we need to center the title or make the buttons full-width.

**Review by karthik-durai — APPROVED** [review]

**Comment by shrinathprabhu** [comment]
> Screenshot 2022-07-26 at 12 14 31 AM
> 
> Looks off on small screens. Check if we need to center the title or make the buttons full-width.

@ajithranka Confirmed with design team, the Text needs to be left aligned. The buttons, I'll add a fix to it

It should look something like this
Screenshot from 2022-07-26 17-34-47

**Comment by shrinathprabhu** [comment]
@ajithranka can you check this in small screens, it looks close to design now

**Comment by ajithranka** [comment]
@shrinathprabhu The app header looks off. Anything to do with this PR?

Screenshot 2022-07-27 at 6 49 08 PM

**Review by ajithranka — COMMENTED** [review]
Wondering if `justify-content: start` looks better on small screen?

https://user-images.githubusercontent.com/11095038/181258496-51e403e7-6108-4482-8645-465bdf610239.mov

**Comment by shrinathprabhu** [comment]
> @shrinathprabhu The app header looks off. Anything to do with this PR?
> 
> Screenshot 2022-07-27 at 6 49 08 PM

Yeah it is caused because of the changes in VButton in this PR,
Fixed the positioning here: https://github.com/arcana-network/website/pull/119/commits/affe6ffcfbb5d04883361741bad16d58831a1da3

Removed underline from button here: https://github.com/arcana-network/website/pull/119/commits/128c44cb6dadb4ff1ec6904c846224c093f91ba4

**Comment by shrinathprabhu** [comment]
@ajithranka fixed both the comments

**Review by ajithranka — APPROVED** [review]

**Pull request merged**
